import type { Metadata } from 'next';
import { PageHero } from '@/components/site/PageHero';
import { Prose } from '@/components/site/Prose';

export const metadata: Metadata = {
  title: 'Terms',
  description: 'The terms for using VivaVoce, including the coaching-not-grading disclaimer.',
};

export default function TermsPage() {
  return (
    <>
      <PageHero
        kicker="Terms"
        title="Terms of use"
        intro="The agreement between you and VivaVoce. Last updated 26 June 2026."
      />
      <Prose>
        <h2>Coaching, not grading</h2>
        <p>
          <strong>
            VivaVoce is an educational coaching tool. It is not an examiner, an
            accreditation body, or an official assessment.
          </strong>{' '}
          The scores and feedback it produces are automated estimates intended to
          help you practise and improve. They are not grades, not predictions of
          your real results, and must not be relied upon as a substitute for your
          institution’s assessment or professional advice.
        </p>

        <h2>Using the service</h2>
        <p>
          You must be old enough to consent to processing of your data in your
          jurisdiction. You agree to use VivaVoce for genuine practice, not to
          abuse, overload, reverse-engineer, or attempt to extract other users’
          data from the service. You’re responsible for the content you record and
          for ensuring you have the right to practise with any material you import.
        </p>

        <h2>Your content</h2>
        <p>
          You keep ownership of your recordings, transcripts, and the decks you
          create. You grant us a limited licence to process that content solely to
          provide the service to you (transcription, evaluation, progress
          tracking) as described in our{' '}
          <a href="/privacy">Privacy Policy</a>.
        </p>

        <h2>AI-generated content</h2>
        <p>
          Questions, feedback, and model answers may be generated by AI and can be
          imperfect or occasionally wrong. Use judgement, especially for factual or
          high-stakes material, and verify against authoritative sources.
        </p>

        <h2>Availability</h2>
        <p>
          We work to keep VivaVoce reliable, but the service is provided “as is”
          without warranties. We may change, suspend, or discontinue features. To
          the extent permitted by law, we are not liable for indirect or
          consequential losses arising from use of the service.
        </p>

        <h2>Ending your use</h2>
        <p>
          You can stop using VivaVoce and delete your account at any time. We may
          suspend accounts that violate these terms or put the service or other
          users at risk.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms? Email{' '}
          <a href="mailto:hello@vivavoce.app">hello@vivavoce.app</a>.
        </p>
        <p>
          This document is provided for transparency and does not constitute legal
          advice.
        </p>
      </Prose>
    </>
  );
}
