import type { Metadata } from 'next';
import Link from 'next/link';
import { Muted, PageHero } from '@/components/site/PageHero';
import { DocSection, Prose } from '@/components/site/Prose';

export const metadata: Metadata = {
  title: 'Terms',
  description: 'The terms for using VivaVoce, including the coaching-not-grading disclaimer.',
};

const toc = [
  { id: 'coaching-not-grading', title: 'Coaching, not grading' },
  { id: 'using-the-service', title: 'Using the service' },
  { id: 'your-content', title: 'Your content' },
  { id: 'ai-generated-content', title: 'AI-generated content' },
  { id: 'availability', title: 'Availability' },
  { id: 'ending-your-use', title: 'Ending your use' },
  { id: 'contact', title: 'Contact' },
] as const;

export default function TermsPage() {
  return (
    <>
      <PageHero
        title={
          <>
            Terms of use. <Muted>Coaching, not grading.</Muted>
          </>
        }
        intro="The agreement between you and VivaVoce."
      />
      <Prose toc={toc} updated="26 June 2026">
        <DocSection id="coaching-not-grading" title="Coaching, not grading">
          <p>
            <strong>
              VivaVoce is an educational coaching tool. It is not an examiner, an
              accreditation body, or an official assessment.
            </strong>{' '}
            The scores and feedback it produces are automated estimates intended to
            help you practise and improve. They are not grades, not predictions of
            your real results, and must not be relied upon as a substitute for your
            institution’s assessment or professional advice.
          </p>
        </DocSection>

        <DocSection id="using-the-service" title="Using the service">
          <p>
            You must be old enough to consent to processing of your data in your
            jurisdiction. You agree to use VivaVoce for genuine practice, not to
            abuse, overload, reverse-engineer, or attempt to extract other users’
            data from the service. You’re responsible for the content you record and
            for ensuring you have the right to practise with any material you import.
          </p>
        </DocSection>

        <DocSection id="your-content" title="Your content">
          <p>
            You keep ownership of your recordings, transcripts, and the decks you
            create. You grant us a limited licence to process that content solely to
            provide the service to you (transcription, evaluation, progress
            tracking) as described in our <Link href="/privacy">Privacy Policy</Link>.
          </p>
        </DocSection>

        <DocSection id="ai-generated-content" title="AI-generated content">
          <p>
            Questions, feedback, and model answers may be generated by AI and can be
            imperfect or occasionally wrong. Use judgement, especially for factual or
            high-stakes material, and verify against authoritative sources.
          </p>
        </DocSection>

        <DocSection id="availability" title="Availability">
          <p>
            We work to keep VivaVoce reliable, but the service is provided “as is”
            without warranties. We may change, suspend, or discontinue features. To
            the extent permitted by law, we are not liable for indirect or
            consequential losses arising from use of the service.
          </p>
        </DocSection>

        <DocSection id="ending-your-use" title="Ending your use">
          <p>
            You can stop using VivaVoce and delete your account at any time. We may
            suspend accounts that violate these terms or put the service or other
            users at risk.
          </p>
        </DocSection>

        <DocSection id="contact" title="Contact">
          <p>
            Questions about these terms? Email{' '}
            <a href="mailto:hello@vivavoce.app">hello@vivavoce.app</a>.
          </p>
          <p className="vv-doc-fine">
            This document is provided for transparency and does not constitute legal
            advice.
          </p>
        </DocSection>
      </Prose>
    </>
  );
}
